-- Migration: Create expenses table
-- Description: Company and project expenses for the OPF-CD system
-- Version: 1.0
-- Date: 2026-02-02

-- Create expense type enum
CREATE TYPE expense_type AS ENUM (
  'recurring',
  'one_off'
);

-- Create expense frequency enum
CREATE TYPE expense_frequency AS ENUM (
  'monthly',
  'quarterly',
  'annual'
);

-- Create expense status enum
CREATE TYPE expense_status AS ENUM (
  'due',
  'paid',
  'overdue'
);

-- Create expenses table
CREATE TABLE expenses (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  amount NUMERIC(15,2) NOT NULL CHECK (amount >= 0),
  currency currency_code NOT NULL,
  type expense_type NOT NULL,
  frequency expense_frequency,
  status expense_status NOT NULL DEFAULT 'due',
  project_id INTEGER REFERENCES projects(id) ON DELETE RESTRICT,
  due_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX idx_expenses_type ON expenses(type);
CREATE INDEX idx_expenses_status ON expenses(status);
CREATE INDEX idx_expenses_project_id ON expenses(project_id);
CREATE INDEX idx_expenses_due_date ON expenses(due_date);
CREATE INDEX idx_expenses_created_at ON expenses(created_at);

-- Add comments for documentation
COMMENT ON TABLE expenses IS 'Company and project expenses - paid expenses cannot be edited';
COMMENT ON COLUMN expenses.name IS 'Expense name or description';
COMMENT ON COLUMN expenses.category IS 'Expense category for grouping and reporting';
COMMENT ON COLUMN expenses.amount IS 'Expense amount - must be non-negative';
COMMENT ON COLUMN expenses.currency IS 'Currency code for the expense amount';
COMMENT ON COLUMN expenses.type IS 'Expense type: recurring or one_off';
COMMENT ON COLUMN expenses.frequency IS 'Recurrence frequency (monthly, quarterly, annual) - only applicable when type = recurring. Future instances generated by service layer.';
COMMENT ON COLUMN expenses.status IS 'Expense payment status';
COMMENT ON COLUMN expenses.project_id IS 'Optional project association - null means company-wide expense';
COMMENT ON COLUMN expenses.due_date IS 'Expense due date';
